site_name: ASTRA

site_url: https://mydomain.org/mysite
docs_dir: docs
repo_url: https://github.com/Kamuish/ASTRA

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.indexes 
    - toc.integrate 
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - HOME: index.md
  - User guides:
    - user_guide/index.md 
    - Installation: user_guide/installation.md
    - Contribution: user_guide/contribution.md
    - Reporting issues: user_guide/issues.md
  - API:
    - api/index.md
    - User configs: api/user_configs.md


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            filters:
              - "!^_"