site_name: ASTRA

site_url: https://mydomain.org/mysite
docs_dir: docs
repo_url: https://github.com/Kamuish/ASTRA

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.indexes 
    - toc.integrate 
    - content.code.copy
    - content.code.select
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - HOME: 
    - Overview: index.md
    - Changelog: changelog.md


  - Quickstart:
    - Basic example: user_guide/basic_example.ipynb
    - Configuration: user_guide/configuration.ipynb
  
  - Spectra:
    - spectra/index.md
    - spectra/open_spectra.ipynb
    - spectra/access_spectra.ipynb
    - spectra/selecting_spectra.ipynb
  
  - Templates:
    - template_creation/index.md
    - Stellar model: template_creation/stellar.ipynb
    - Telluric model: template_creation/telluric.ipynb

  - Advanced:
    - Interpolation: advanced/spectra_interpolation.ipynb
    - Normalization: advanced/spectra_normalization.ipynb
  
  - API:
    - api/index.md
    - User configs: api/user_configs.md
    - Frame: api/Frame.md

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            filters:
              - "!^_"